services:
  - type: web
    name: projectnext-api
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
